#DESeq Testing Script using whole RNA_Seq cohort with relapse information.
#Excludes:

library(BiocInstaller)
?BiocUpgrade
source("https://bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")
biocLite("DESeq2")
library("DESeq")
library("DESeq2")
??DESeq2
countdesign = read.csv("H:/Alex/RNA_Seq/.txt", header=TRUE, sep= "\t")
cds = newCountDataSetFromHTSeqCount(countdesign, directory= "H:/Alex/RNA_Seq/")
#We have now loaded in the two count files using newCountDataSetFromHTSeqCount 
#Next step is normalisation using "estimateSizeFactors" to get size factors to remove the impact of 
#differing sequencing depth on the samples.
cds = estimateSizeFactors(cds)
sizeFactors(cds)
head(counts(cds, normalized=TRUE)) #shows the values of each count divided by samples respective sizeFactor
cds = estimateDispersions(cds, method='blind') #estimating variance. As no repeats at the moment for counts,
#the method='blind' function is needed.
str(fitInfo(cds))
plotDispEsts(cds) #draws the plot comparing dispersion to mean of normalised counts
head(fData(cds)) #to be used for quality control alongside plot... not entirely sure what really to look for
res = nbinomTest(cds,"Diagnostic","Relapse") #because in the estimateDispersions we had one of each condition 
#and had to use method='blind', this will not yield any useful results. 
head(res)
plotMA(res)
hist(res$pval, breaks=100, col="skyblue", border="slateblue", main="")
################################################################################################################
#Now to start again with my own data
BNHL.relapse.countdesign = read.csv("H:/Alex/RNA_Seq/Relapse_Non-relapse_CountDesign.txt", sep='\t')
#Just waiting on the last two htseq files to start this bit:
CountDataSet.relapse = newCountDataSetFromHTSeqCount(BNHL.relapse.countdesign, directory="H:/Alex/RNA_Seq/HTSeq")
CountDataSet.relapse = estimateSizeFactors(CountDataSet.relapse)
sizeFactors(CountDataSet.relapse)
head(counts(CountDataSet.relapse, normalized=TRUE))
CountDataSet.relapse = estimateDispersions(CountDataSet.relapse)
str(fitInfo(CountDataSet.relapse))
plotDispEsts(CountDataSet.relapse)
head(fData(CountDataSet.relapse))
COUNTresult.relapse = nbinomTest(CountDataSet.relapse,"Non-Relapse","Relapse")
head(COUNTresult.relapse)
plotMA(data.frame(result.relapse))
hist(result.relapse$pval, breaks=100, col="skyblue", border="slateblue", main="")
#According to the DESeq2 manual, the above analysis can be done at once with the DESeq() function and results generated by the results() function.
#Will use this "quicker" method first, and then decide if results look reasonable.

#First, loading data in is  different, need to use DESeqDataSetFromHTSeqCount rather than newCountDataSet...
#Also add design=condition
BNHL.relapse.countdesign = read.csv("H:/Alex/RNA_Seq/Relapse_Non-relapse_CountDesign.txt", sep='\t')
?DESeqDataSetFromHTSeqCount
DESeqDataSet.relapse = DESeqDataSetFromHTSeqCount(BNHL.relapse.countdesign, directory="H:/Alex/RNA_Seq/HTSeq", design= ~ condition)
#The above line created a value "first_time"??

#First, set the factor levels correctly, or the package will treat them alphabetically.
#DESeqDataSet.relapse$condition <- factor(DESeqDataSet.relapse$condition, levels ="Non-Relapse","Relapse")
#factor level above lead to errors so instead of trying it, go straight to relevel below.
DESeqDataSet.relapse$condition <- relevel(DESeqDataSet.relapse$condition, ref="NonRelapse")
DESeqDataSet.relapse <- DESeq(DESeqDataSet.relapse)
result.relapse <- results(DESeqDataSet.relapse)
head(result.relapse)
setwd("H:/Alex/RNA_Seq")
write.csv(result.relapse,"result1_relapse.txt", sep='\t')
#As far as I can tell, the rest should be as above
#Can also order our results by smallest adj.pvalue:
pvalordered.result.relapse <- result.relapse[order(result.relapse$padj),]
pvalordered2.result.relapse <- result.relapse[order(result.relapse$pvalue),]
head(pvalordered2.result.relapse)
#Summarise the results:
summary(result.relapse) #at the moment this gives no up- or down-regulated genes?!
sum(result.relapse$padj < 0.1, na.rm=TRUE)
sum(result.relapse$pvalue < 0.1, na.rm=TRUE)
?plotMA
head(result.relapse)
is.data.frame(DESeqDataSet.relapse)
plotMA(DESeqDataSet.relapse)
plotMA(data.frame(result.relapse))
hist(result.relapse$pvalue, breaks=100, col="skyblue", border="slateblue", main="")
hist(result.relapse$padj, breaks=100, col="skyblue", border="slateblue", main="")


#Now how do I get my gene list? 

